//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NearByCore.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("NearByCore.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string UnExpectedCulture {
            get {
                return ResourceManager.GetString("UnExpectedCulture", resourceCulture);
            }
        }
        
        internal static string ErrorInteger {
            get {
                return ResourceManager.GetString("ErrorInteger", resourceCulture);
            }
        }
        
        internal static string ErrorString {
            get {
                return ResourceManager.GetString("ErrorString", resourceCulture);
            }
        }
        
        internal static string BindableObjectError {
            get {
                return ResourceManager.GetString("BindableObjectError", resourceCulture);
            }
        }
        
        internal static string NoPriceDetails {
            get {
                return ResourceManager.GetString("NoPriceDetails", resourceCulture);
            }
        }
        
        internal static string Unrated {
            get {
                return ResourceManager.GetString("Unrated", resourceCulture);
            }
        }
        
        internal static string LocationPermission {
            get {
                return ResourceManager.GetString("LocationPermission", resourceCulture);
            }
        }
        
        internal static string LocationPermissionDenied {
            get {
                return ResourceManager.GetString("LocationPermissionDenied", resourceCulture);
            }
        }
        
        internal static string LocationAlertMessage {
            get {
                return ResourceManager.GetString("LocationAlertMessage", resourceCulture);
            }
        }
        
        internal static string UnableToFindLocation {
            get {
                return ResourceManager.GetString("UnableToFindLocation", resourceCulture);
            }
        }
        
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        internal static string Understood {
            get {
                return ResourceManager.GetString("Understood", resourceCulture);
            }
        }
        
        internal static string Places {
            get {
                return ResourceManager.GetString("Places", resourceCulture);
            }
        }
        
        internal static string SortByDistance {
            get {
                return ResourceManager.GetString("SortByDistance", resourceCulture);
            }
        }
        
        internal static string SortByRating {
            get {
                return ResourceManager.GetString("SortByRating", resourceCulture);
            }
        }
        
        internal static string OrderByDistance {
            get {
                return ResourceManager.GetString("OrderByDistance", resourceCulture);
            }
        }
        
        internal static string OrderByRating {
            get {
                return ResourceManager.GetString("OrderByRating", resourceCulture);
            }
        }
        
        internal static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        internal static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        internal static string NoNearbyPlacesFound {
            get {
                return ResourceManager.GetString("NoNearbyPlacesFound", resourceCulture);
            }
        }
        
        internal static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string NoItemsFound {
            get {
                return ResourceManager.GetString("NoItemsFound", resourceCulture);
            }
        }
    }
}
